export const NUEVA_NOVEDAD = "NUEVA_NOVEDAD";
export const CAMBIAR_CAMPO_NOVEDAD = "CAMBIAR_CAMPO_NOVEDAD";
export const NUEVO_RECLAMO = "NUEVO_RECLAMO";
export const FIND_BILL = "FIND-BILL";
export const REINICIAR_FORMULARIO_NOVEDADES = "REINICIAR_FORMULARIO_NOVEDADES";

export const CAMBIAR_DATOS_USUARIO = "CAMBIAR_DATOS_USUARIO";
export const ESTABLECER_ROL = "ESTABLECER_ROL";
export const ESTABLECER_EMPRESA = "ESTABLECER_EMPRESA";
