export const NUEVA_NOVEDAD = "NUEVA_NOVEDAD";
export const NUEVO_RECLAMO = "NUEVO_RECLAMO";

export const CAMBIAR_DATOS_USUARIO = "CAMBIAR_DATOS_USUARIO";
export const ESTABLECER_ROL = "ESTABLECER_ROL";
export const ESTABLECER_EMPRESA = "ESTABLECER_EMPRESA";
